import type { Metadata } from "next";
import Header from "@/components/Header";
import "../globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { SanityLive } from "@/sanity/lib/live";
import { VisualEditing } from "next-sanity";
import { draftMode } from "next/headers";
import { DisableDraftMode } from "@/components/DisableDraftMode";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async  function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider dynamic>
      <html lang="en">
        <body>
          {
            (await draftMode()).isEnabled && (
              <>
              <DisableDraftMode/>
              <VisualEditing/>
              </>
            )
          }
          <main>
            <Header/>
            {children}
            </main>
            <SanityLive/>
        </body>
      </html>
    </ClerkProvider>
  );
}
